export enum TicketStatus {
  EN_ANALISIS = 'EN ANALISIS',
  EN_PROCESO = 'EN PROCESO',
  ENTREGADO_A_LT = 'ENTREGADO A LT',

  DESPLIEGUE_A_DESARROLLO = 'DESPLIEGUE A DESARROLLO',
  EN_REVISION_DESARROLLO = 'EN REVISION DESARROLLO',
  APROBADO_PARA_QA = 'APROBADO PARA QA',

  DESPLIEGUE_A_QA = 'DESPLIEGUE A QA',
  EN_REVISION_QA = 'EN REVISION QA',
  APROBADO_QA = 'APROBADO QA',
  PENDIENTE_CERTIFICACION = 'PENDIENTE CERTIFICACION',
  CERTIFICADO = 'CERTIFICADO',

  DESPLIEGUE_A_PRODUCCION = 'DESPLIEGUE A PRODUCCION',
  FINALIZADO = 'FINALIZADO',

  BLOQUEO = 'BLOQUEO',
  DEVUELTO = 'DEVUELTO',
  ROLLBACK = 'ROLLBACK',
}
